### ISSUE TITLE
Docs: Add example with Custom Provider

### ISSUE THREAD

**Issue by cbzehner** [jebrosen/rocket_oauth2#12]
Hi, I've been using `rocket_oauth2` on the side to try and implement a Slackbot with some basic functionality. It took me quite a while to figure out how specify a custom provider so I'd like to contribute back an example of how to set one up.

I already put up a draft pull request https://github.com/jebrosen/rocket_oauth2/pull/11 based on the Slack integration I set up, but ran into some issues with the `basic.identity` scope. I'd appreciate any insights on how to fix this. If it doesn't seem reasonable to fix (I don't expect anyone here to be supporting specific OAuth2 implementations!) would you mind suggesting another API we could implement to showcase how to use custom providers?

My initial goal was to provide an example as similar as possible to the existing `examples/user_info_hyper_sync_rustls` so it readers would have an easy time spotting differences.

**Comment by jebrosen** [comment]
#11 is merged and I added some additional documentation on provider specification to the crate-level docs, so I will close this particular issue. I do want to continue to improve the documentation and examples overall, though.
