### ISSUE TITLE
Callback fails to run if request parameters are in the wrong order

### ISSUE THREAD

**Issue by sd2k** [jebrosen/rocket_oauth2#15]
The parameters to the callback in the examples and docs look like this:

```
#[get("/auth/microsoft")]
fn microsoft_callback(
    token: TokenResponse<MicrosoftUserInfo>,
    mut cookies: Cookies<'_>,
) -> Result<Redirect, Debug<Error>> {
    ...
}
```

I was playing around just now and for some reason swapped the two parameters so that the signature looked like this:

```
#[get("/auth/microsoft")]
fn microsoft_callback(
    mut cookies: Cookies<'_>,
    token: TokenResponse<MicrosoftUserInfo>,
) -> Result<Redirect, Debug<Error>> {
    ...
}
```

And when that route is hit, the following error is shown in the logs:

```
    => Matched: GET /auth/microsoft (microsoft_callback)
    => Error: Multiple `Cookies` instances are active at once.
    => An instance of `Cookies` must be dropped before another can be retrieved.
    => Warning: The retrieved `Cookies` instance will be empty.
Warning: The OAuth2 state returned from the server did not match the stored state.
    => Outcome: Failure
    => Warning: Responding with 400 Bad Request catcher.
    => Response succeeded.
```

This presumably makes sense given a bit of knowledge of Rocket's request handling, since `TokenResponse`'s `FromRequest` impl needs mutable access the cookies and they're already borrowed mutably by `mut cookies`, but it's a bit surprising - probably nothing that documentation can't manage.

**Comment by jebrosen** [comment]
This is explained by [the Rocket guide](https://rocket.rs/v0.4/guide/requests/#one-at-a-time), but it's not easily "guessable" that `TokenRequest` uses `Cookies`. The current message ``Warning: The OAuth2 state returned from the server did not match the stored state.`` is misleading. I will definitely change that to something like ``Error: Unable to access request cookies. Is a Cookies guard already active?``

> probably nothing that documentation can't manage.

Do you have any suggestions on where to put this documentation? As in, the API docs for `TokenResponse`, the top-level documentation/examples, or in the `examples/` directory?

**Comment by sd2k** [comment]
I can see it fitting in all of those places, but the top-level docs/examples and API docs for `TokenResponse` would be most visible I think.

**Comment by jebrosen** [comment]
Alright, I made the following two changes:

* e0ed071 changes the log message for "cookie missing" vs "cookie mismatch". Unfortunately there's not a good way to distinguish "Cookies guard in the wrong order" from "the cookie is missing", so the error message is a "best effort".
* 7b825fe adds some explanation to the docs and doc examples.

I think this addresses your concerns.

**Comment by sd2k** [comment]
That looks fantastic, thanks!
