### ISSUE TITLE
Plans for Rocket v0.5

### ISSUE THREAD

**Issue by cbzehner** [jebrosen/rocket_oauth2#27]
👋 Hi Jeb,

Just wondering - what are the plans for this crate with the upcoming Rocket v0.5 release (which I'm sure is keeping you plenty busy 😅)?

I've used this with v0.4 and really appreciated the ergonomics of it - I'd like to use it with a new project based on the v0.5-rc1 branch of Rocket but am not sure where to get started.

If you're interested, I'd be happy to help fix some of the type errors that come up but there's probably some larger changes needed with the ability to use async (does `hyper_sync_rustls` still make sense?) and the move to Figment.

**Comment by jebrosen** [comment]
Sorry, I think I haven't documented this well and/or changed the right settings on the repository. Development of 0.5 has been in the `next` branch, with a [crates.io release] for `0.5.0-rc.1` (coincidentally matching the version of `rocket`'s rc release this time around). A migration guide is in the CHANGELOG: <https://github.com/jebrosen/rocket_oauth2/blob/next/CHANGELOG.md#050-rc1---2021-06-09>.

I think it includes most of the changes accomplished in your PR, but if I missed something please let me know!

[crates.io release]: https://github.com/jebrosen/rocket_oauth2/tree/next

**Comment by cbzehner** [comment]
Thank you. 🙇  It took me about an hour to port an existing service from `0.4` release to `0.5.0-rc.1`. Super fast and easy. 🥇 

One note: It might be nice to have an example that doesn't rely on the `Rocket.toml` file - most of the other values I had stored here have moved into environment variables as I've upgraded Rocket. I haven't spent the time to figure out the appropriate way to integrate the `oauth.<provider>` settings though so I'm just keeping `Rocket.toml` around for now.

**Comment by jebrosen** [comment]
> One note: It might be nice to have an example that doesn't rely on the Rocket.toml file

Sure! Something like this should work (based on the `user_info` example):

`ROCKET_OAUTH='{ google = { provider = "Google", client_id = "<client_id>", client_secret = "<client_secret>", redirect_uri = "http://localhost:8000/auth/google" } }'`

**Comment by jebrosen** [comment]
I've just committed 1b6cb28, which I think resolves this.
