### ISSUE TITLE
How do we use rocket_oauth2 for Facebook?

### ISSUE THREAD

**Issue by viraatdas** [jebrosen/rocket_oauth2#30]
[global.oauth.facebook]
provider = { auth_uri = "https://graph.facebook.com/oauth/authorize", token_uri = "https://graph.facebook.com/oauth/access_token" }
client_id = ""
client_secret = ""
redirect_uri = "http://localhost:8000/auth/facebook"

This is my Rocket.toml but I'm not sure why I'm not able to create a login flow. 

Thanks for the help!

**Comment by jebrosen** [comment]
Hello, and sorry for the (very) late reply. For posterity:

> This is my Rocket.toml but I'm not sure why I'm not able to create a login flow.

`Rocket.toml` is only one of several pieces required, so there could be any number of issues here:

* Misconfiguration of your facebook app
* Missing or wrong `#[get]` routes
* Security restrictions or limitations in browsers, especially related to cookies and redirects

To answer this sort of question, it would be very useful to know which step of the flow (site -> facebook -> site) "breaks" first and what error logs are created, if any.
