### ISSUE TITLE
What's the difference between rocket_oauth2 and the OAuth2 crate?

### ISSUE THREAD

**Issue by huangjj27** [jebrosen/rocket_oauth2#31]
I notice that `rocket_oauth2` is implemented without `oauth2` which I think provide much more functionality. Why rocket_oauth2 decided to implement differently?

**Comment by jebrosen** [comment]
That was a while ago, but the main two reasons I remember were:

* `rocket_oauth2` depends on the same underlying cryptography libraries as `rocket` itself (i.e. `rustls`, `ring`) for its HTTPS client. In contrast, I believe (at the time!) that `oauth2` supported only other cryptography libraries.
* `rocket_oauth2` *only* supports the "Authorization Code" grant type (https://www.rfc-editor.org/rfc/rfc6749.html#section-4.1), greatly simplifying both the API surface and implementation.

It's very possible that `oauth2` is a better choice these days for most projects or as the underlying backend for this crate, but I have no recent knowledge or experience with it myself.
