### ISSUE TITLE
Cookies in rocket_oauth2 v0.4.1 not working for rocket v0.5.0-rc.2

### ISSUE THREAD

**Issue by elonaire** [jebrosen/rocket_oauth2#41]
`use rocket::http::{Cookies};`
The above import is not working for rocket v0.5.0-rc.2. I have tried switching to `CookieJar` but it seems some changes need to be made to rocket_oauth2 lib to accommodate rocket v0.5.0-rc.2 `CookieJar`.

**Comment by jebrosen** [comment]
Yes, `rocket_oauth2 v0.4.x` is not compatible with `rocket 0.5.0-rc.2` (and probably won't ever be).

Instead you can use `rocket_oauth2 0.5.0-rc.1` (see also the `next` branch: https://github.com/jebrosen/rocket_oauth2/tree/next) with `rocket 0.5.0-rc.1`, and *possibly* with `rocket 0.5.0-rc.2`. I plan to review that soon and make a new release if it makes sense.
