### ISSUE TITLE
Multiple redirect URIs?

### ISSUE THREAD

**Issue by Atlinx** [jebrosen/rocket_oauth2#47]
Is it possible to use different redirect URLs? I'd like to have OAuth on web and mobile platforms all be redirected through my backend, however, they require different redirect URIs.

**Comment by jebrosen** [comment]
`rocket_oauth2` currently only supports one redirect URL per configuration, but it does support multiple configurations. The main [example](https://github.com/jebrosen/rocket_oauth2/tree/master/examples/user_info_hyper_sync_rustls) project has three different redirect URLs; in this example each is for a different identity provider, but this same approach should work for the same identity provider.

In principle multiple redirect URLs should be possible, but I'm concerned about the complexity tradeoff and would prefer to avoid it.
