### ISSUE TITLE
How to implement dynamic redirect_uris

### ISSUE THREAD

**Issue by upachler** [jebrosen/rocket_oauth2#5]
Hi there,

I'm currently toying around with rocket/_oauth2 and wondering about a very common auth scenario:

User...
* logs in to webapp
* either lets their session expire or bookmarks current route/URI
* user comes back to URI without being logged in
* user sees login prompt and logs in again
-> expectation: user ends up at the same URI as before

After the last step, the expectation is that the user will return to the same route that he/she was at before (the one he/she bookmarked or let the session expire on).

OAuth2 supports this via the ?state=.., which rocket_oauth2 happily fills with its own state as it appears. 

So how would I implement the above scenario?

Cheers,

Uwe

**Comment by jebrosen** [comment]
`state` is used like a CSRF token and can't be repurposed for this.

One option would be to set a cookie, such as "return_to", at the same time that you redirect an expired session to the login page. In the auth callback, you can check that cookie and redirect back to that stored URL if it's set.

**Comment by upachler** [comment]
Hi Jeb, 

The way I read the standard I'd assume that the 'local state' is encoded in the redirect URI. See here (especially point C):
https://tools.ietf.org/html/rfc6749#section-4.1

This also coincides whith what I'm observing on the IDP I'm using (Keycloak) - when you access the users's account page via a link without being loggedin, it encodes the current route of it's angular FE in a ?path=.. parameter, which is retained when redirecting back after a successful login. So yeah, maybe the 'state' parameter is not the way to go, but it still looks to me that the redirect URI should be dynamic. If it were the same all the time, you could encode it fixed in the client definition of the IDP, and not pass the same thing around every time you log in.

**Comment by jebrosen** [comment]
> The way I read the standard I'd assume that the 'local state' is encoded in the redirect URI. See here (especially point C):

I'll slightly downgrade what I said: this library uses `state` like a CSRF token (as recommended) and I don't want to change that. I might consider *adding* additional data, but being able to the state wholesale breaks the abstraction this library is intended to provide.

> it encodes the current route of it's angular FE in a ?path=.. parameter, which is retained when redirecting back after a successful login.

I'm not sure I follow. Are you saying that a `path` parameter is given to the Authorization Endpoint, and the service forwards that on to the Redirection Endpoint? I don't see anything in the RFC requiring this behavior, and I don't want to rely on it in any way.

**Comment by upachler** [comment]
> I'm not sure I follow. Are you saying that a path parameter is given to the Authorization Endpoint, and the service forwards that on to the Redirection Endpoint? I don't see anything in the RFC requiring this behavior, and I don't want to rely on it in any way.

Yes, that's what's happening, at least in Keycloak. Other OPs might do the same, because it's the only other way to pass information around if you don't want to or can't rely on cookies. And there are good reasons not to rely on them; in the EU there are even privacy laws governing their use. 

But being able to add information in to state=.. sounds like a good idea as well, and it follows the standard quite literally.

**Comment by jebrosen** [comment]
> Yes, that's what's happening, at least in Keycloak. Other OPs might do the same, because it's the only other way to pass information around if you don't want to or can't rely on cookies.

Ad-hoc additions like that are pretty frustrating to deal with as a generic library, because they won't be supported or even implemented the same way across different providers.

> And there are good reasons not to rely on them; in the EU there are even privacy laws governing their use.

Note that the `state` is already stored in a `Cookie` (it must be, in order to verify it later). As far as I can tell this usage falls under 'strictly necessary', but I have not consulted with a lawyer.

> But being able to add information in to state=.. sounds like a good idea as well, and it follows the standard quite literally.

I will think more about adding custom data to `state`, but it raises some annoying issues. I think it will require changing the signatures of `get_redirect` and possibly also `authorization_uri`, and it won't be usable by the auto-generated login route if it's being used. Security of the data is another concern; I'm hesitant about sending it to the provider in plain text.

**Comment by jeluard** [comment]
Being able to pass random data in state on top of CSRF token is a common pattern AFAIK. It can be used to persist query params after the OAuth redirection for instance.

It would be useful to allow some arbitrary data to be provided and retrieved on top of the CSRF token.

**Comment by jebrosen** [comment]
I'm rejecting this feature request as it has been proposed. In short, implementing this feature would require significant effort (secrets management and encryption) for little gain (the benefit of not needing another cookie or session storage).

`state` "SHOULD" be used to defend against CSRF, described further under <https://datatracker.ietf.org/doc/html/rfc6749#section-10.12>. The current implementation is that `state` is simply a randomly generated value (i.e. non-guessable) and is stored in a private cookie (to bind it to the session). By necessity, the cookie is stored on the client. At that point, why not use another cookie or session storage for the redirect destination? I am unconvinced that any cookie or privacy laws are a real barrier in this scenario: compared to actually processing user data or making API calls on behalf of the authenticated user after the token is acquired, storing the CSRF token in a cookie is nothing.

So, this feature does not seem necessary. It would still be nice to have! But... if I as a new user of the library were to add custom data to `state`, I would normally expect it to be encrypted to protect it from the authorization server. This would require something like SergioBenitez/Rocket#477, or for `rocket_oauth2` to implement its own secrets management or encryption, neither of which are appealing options.
