### ISSUE TITLE
How secure is this?

### ISSUE THREAD

**Issue by BenMcAvoy** [jebrosen/rocket_oauth2#50]
Sorry, I am rather new to OAuth and especially integrating it into Rust.

I am using Microsoft and pulling the email address from the microsoft account in `/auth/microsoft` into a cookie as follows:
```rust
    cookies.add_private(
        Cookie::build(("email", user_info.email))
            .same_site(SameSite::Lax)
            .build(),
```

I noticed that there is a cookie on the client side. 

Imagine I implement another route as follows:
```rust
#[get("/other")]
async fn other(user: User) -> String {
    user.email
}
```

Also imagine it does something sensitive rather than returning the email address. Apart from stealing a legitimate token/email cookie. Is this secure? Is there no way someone can just impersonate someone else or simply change there email address value without obtaining a legitimate token.

E.g., can a user simply change their email cookie to some random string with a special encoding or is it secure?

My data on the server-side will most likely be tied to the users email and so I do not want the user to be able to change this without obtaining a valid token/cookie (I am currently ignoring cookie grabbing with XSS at the moment as it should not be a problem for me)

**Comment by jebrosen** [comment]
> Also imagine it does something sensitive rather than returning the email address. Apart from stealing a legitimate token/email cookie. Is this secure? Is there no way someone can just impersonate someone else or simply change there email address value without obtaining a legitimate token.
>
> E.g., can a user simply change their email cookie to some random string with a special encoding or is it secure?

Generally speaking, private cookies **are secure** against this kind of attack - see this from the guide at https://rocket.rs:

> Thus, private cookies cannot be inspected, tampered with, or manufactured by clients.
> -- Rocket guide, <https://rocket.rs/v0.5/guide/requests/#private-cookies>

The encryption+decryption is done server side, with a secret key specified in the server configuration.

---

> My data on the server-side will most likely be tied to the users email and so I do not want the user to be able to change this without obtaining a valid token/cookie (I am currently ignoring cookie grabbing with XSS at the moment as it should not be a problem for me)

This is serviceable, but does have a few important limitations worth considering depending on your application's needs - mainly, expiration and login flexibility. Authenticating with a cookie carrying only an email address makes it a "forever token" to the account, so you may prefer to include additional details such as an issued-at time, either in the cookie itself or on the server side. If differentiating between sessions or a "sign out of other sessions" feature is desired, a session id tracked in a database might be a better choice. And finally, using a unique long-lasting user identifier other than email address would make it easier to handle users changing their email address or adding/removing other authentication methods. In the end it really depends on your specific application's needs: email-only could be sufficient especially at high trust levels, but it is a bit limited and may need to be replaced by something more sophisticated later.

I'm going to close this issue as it's not especially related to `rocket_oauth2` itself, but please do feel free to ask any follow-up questions in this thread!
